const express = require("express");
const axios = require("axios");
const fs = require("fs");

const app = express();
const port = 8521;
const intervalTime = 1 * 60 * 1000; // 1 menit dalam milidetik

// Konfigurasi AdGuard Home
const adguardApiUrl = "http://16.20.20.20:2525/control/querylog";
const adguardAuth = {
  username: "Hafri",
  password: "Loveisproblem@2611",
};

// --- DAFTAR DOMAIN YANG AKAN DIPROSES ---
const domainsSosmed = [
  "youtube",
  "ytimg",
  "facebook",
  "instagram",
  "akamai",
  "googlevideo",
  "lazada",
  "shopee",
  "snackvideo",
  "bukalapak",
  "tokopedia",
  "netflix",
  "twitter",
  "tiktok",
];

const domainsBlock = [
  "speedtest",
  "xnxx",
  "vpn",
  "arcai",
  "netcut",
  "xhamster",
  "javhd",
  "bokep",
];

// Fungsi untuk menghasilkan dan menyimpan file Mikrotik
const generateMikrotikScript = async () => {
  let scriptContent = `# Mikrotik Address-List generated by Express.js on ${new Date().toISOString()}\n\n`;

  try {
    const response = await axios.get(adguardApiUrl, { auth: adguardAuth });
    const queries = response.data.data;
    const processedDomains = new Set();

    for (const query of queries) {
      if (query.status === "NOERROR") {
        let domain = query.question.name;

        if (domain && domain.endsWith(".")) {
          domain = domain.slice(0, -1);
        }

        if (domain && !processedDomains.has(domain)) {
          if (domainsSosmed.some((d) => domain.includes(d))) {
            // Perbaikan utama: Tambahkan logika pengecekan duplikat di skrip Mikrotik
            scriptContent += `:local exists [/ip firewall address-list find address="${domain}" list="Sosmed"]\n`;
            scriptContent += `:if (\$exists = "") do={ /ip firewall address-list add list="Sosmed" address="${domain}" comment="${domain}" timeout=1d00:00:00 }\n`;
            processedDomains.add(domain);
          } else if (domainsBlock.some((d) => domain.includes(d))) {
            // Perbaikan utama: Tambahkan logika pengecekan duplikat di skrip Mikrotik
            scriptContent += `:local exists [/ip firewall address-list find address="${domain}" list="Block"]\n`;
            scriptContent += `:if (\$exists = "") do={ /ip firewall address-list add list="Block" address="${domain}" comment="${domain}" timeout=1d00:00:00 }\n`;
            processedDomains.add(domain);
          }
        }
      }
    }

    fs.writeFileSync("mikrotik_list.rsc", scriptContent);
    console.log(
      `Script Mikrotik berhasil diperbarui pada ${new Date().toISOString()}`
    );
  } catch (error) {
    console.error(
      `[Error] Gagal mengambil log dari AdGuard Home: ${error.message}`
    );
  }
};

setInterval(generateMikrotikScript, intervalTime);

app.get("/mikrotik_list.rsc", (req, res) => {
  if (fs.existsSync("mikrotik_list.rsc")) {
    res.sendFile("mikrotik_list.rsc", { root: "." });
  } else {
    res
      .status(404)
      .send(
        "File mikrotik_list.rsc belum dibuat. Tunggu hingga interval pertama selesai."
      );
  }
});

app.listen(port, () => {
  console.log(`Express server running on http://localhost:${port}`);
  console.log(
    "Fungsi pembaruan otomatis dimulai, file akan diperbarui setiap 1 menit."
  );
  generateMikrotikScript();
});
