const express = require('express');
const axios = require('axios');

const app = express();
const port = 8521;

// Konfigurasi AdGuard Home
const adguardApiUrl = 'http://16.20.20.20:2525/control/querylog'; // Ganti dengan IP AdGuard Home Anda
const adguardAuth = {
    username: 'Hafri',
    password: 'Loveisproblem@2611'
};

// --- DAFTAR DOMAIN YANG AKAN DIPROSES ---
// Tambahkan domain-domain yang ingin Anda masukkan ke address-list "Sosmed"
const domainsSosmed = [
    'youtube.com',
    'facebook.com',
    'instagram.com',
    'twitter.com',
    'tiktok.com'
    // Tambahkan domain lain di sini
];

// Tambahkan domain-domain yang ingin Anda masukkan ke address-list "Block"
const domainsBlock = [
    'situs-judi.com',
    'situs-phising.net',
    'situs-spam.org'
    // Tambahkan domain lain di sini
];

// Endpoint untuk Mikrotik
app.get('/mikrotik_list.rsc', async (req, res) => {
    let scriptContent = `# Mikrotik Address-List generated by Express.js on ${new Date().toISOString()}\n\n`;

    // Hapus address-list lama sebelum membuat yang baru
    scriptContent += `/ip firewall address-list remove [find list="Sosmed"]\n`;
    scriptContent += `/ip firewall address-list remove [find list="Block"]\n\n`;

    try {
        const response = await axios.get(adguardApiUrl, {
            auth: adguardAuth
        });

        const queries = response.data.data;
        const processedDomains = new Set();

        for (const query of queries) {
            // Hanya proses query yang berhasil (status NOERROR) dan memiliki jawaban type A (IPv4)
            if (query.status === 'NOERROR' && query.answer && query.answer[0]?.type === 'A') {
                const domain = query.question.name;
                const ip = query.answer[0]?.value;

                // Pastikan domain dan IP tersedia dan belum diproses sebelumnya
                if (domain && ip && !processedDomains.has(domain)) {
                    // Cek apakah domain termasuk dalam daftar "Sosmed"
                    if (domainsSosmed.some(d => domain.includes(d))) {
                        scriptContent += `/ip firewall address-list add list="Sosmed" address="${ip}" comment="${domain}" timeout=1d00:00:00\n`;
                        processedDomains.add(domain);
                    // Cek apakah domain termasuk dalam daftar "Block"
                    } else if (domainsBlock.some(d => domain.includes(d))) {
                        scriptContent += `/ip firewall address-list add list="Block" address="${ip}" comment="${domain}" timeout=1d00:00:00\n`;
                        processedDomains.add(domain);
                    }
                }
            }
        }
        
        res.set('Content-Type', 'text/plain');
        res.send(scriptContent);

    } catch (error) {
        console.error('Failed to fetch AdGuard Home query log:', error.message);
        res.status(500).send('Error fetching data from AdGuard Home.');
    }
});

// Mulai server
app.listen(port, () => {
    console.log(`Express server running on http://localhost:${port}`);
});