# Mikrotik Address-List generated by Express.js on 2025-08-05T00:49:48.313Z

:local exists [/ip firewall address-list find address="a1345.b.akamai.net" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="a1345.b.akamai.net" comment="a1345.b.akamai.net" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="v9-id.tiktokcdn.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="v9-id.tiktokcdn.com" comment="v9-id.tiktokcdn.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="rr1---sn-apou5n5gu5-jb3s.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="rr1---sn-apou5n5gu5-jb3s.googlevideo.com" comment="rr1---sn-apou5n5gu5-jb3s.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="rr1---sn-apou5n5gu5-jb36.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="rr1---sn-apou5n5gu5-jb36.googlevideo.com" comment="rr1---sn-apou5n5gu5-jb36.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="redirector.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="redirector.googlevideo.com" comment="redirector.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="a464.v.akamai.net" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="a464.v.akamai.net" comment="a464.v.akamai.net" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="a158.b.akamai.net" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="a158.b.akamai.net" comment="a158.b.akamai.net" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="a311.dscd.akamai.net" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="a311.dscd.akamai.net" comment="a311.dscd.akamai.net" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="web.facebook.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="web.facebook.com" comment="web.facebook.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="p16-pu-sign-useast8.tiktokcdn-us.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="p16-pu-sign-useast8.tiktokcdn-us.com" comment="p16-pu-sign-useast8.tiktokcdn-us.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="a1445.b.akamai.net" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="a1445.b.akamai.net" comment="a1445.b.akamai.net" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="r4.sn-npoe7ney.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="r4.sn-npoe7ney.googlevideo.com" comment="r4.sn-npoe7ney.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="pull-flv-f64-va01.tiktokcdn.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="pull-flv-f64-va01.tiktokcdn.com" comment="pull-flv-f64-va01.tiktokcdn.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="pull-flv-l10-sg01.tiktokcdn.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="pull-flv-l10-sg01.tiktokcdn.com" comment="pull-flv-l10-sg01.tiktokcdn.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="r5.sn-npoe7ns6.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="r5.sn-npoe7ns6.googlevideo.com" comment="r5.sn-npoe7ns6.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="r3.sn-npoldn7s.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="r3.sn-npoldn7s.googlevideo.com" comment="r3.sn-npoldn7s.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="a1931.dscgi3.akamai.net" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="a1931.dscgi3.akamai.net" comment="a1931.dscgi3.akamai.net" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="r3.sn-npoeener.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="r3.sn-npoeener.googlevideo.com" comment="r3.sn-npoeener.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="r2.sn-npoldn76.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="r2.sn-npoldn76.googlevideo.com" comment="r2.sn-npoldn76.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="r3.sn-npoe7ne6.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="r3.sn-npoe7ne6.googlevideo.com" comment="r3.sn-npoe7ne6.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="r1.sn-npoe7ns6.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="r1.sn-npoe7ns6.googlevideo.com" comment="r1.sn-npoe7ns6.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="r4.sn-a5mlrnlz.googlevideo.com" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="r4.sn-a5mlrnlz.googlevideo.com" comment="r4.sn-a5mlrnlz.googlevideo.com" timeout=1d00:00:00 }
:local exists [/ip firewall address-list find address="a1987.dscd.akamai.net" list="Sosmed"]
:if ($exists = "") do={ /ip firewall address-list add list="Sosmed" address="a1987.dscd.akamai.net" comment="a1987.dscd.akamai.net" timeout=1d00:00:00 }
